apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-secret: TkF0dXJlQXl1dDIwMjNMTGND  # Base64 encoded "NAtureAyut2023LLcC"
  jwt-refresh-secret: TkF0dXJlQXl1dDIwMjNMTGNDUkVGUkVSRVNI  # Base64 encoded "NAtureAyut2023LLcCREFRERESH"
